### ISSUE TITLE
Missing AKS deployments scripts

### ISSUE THREAD

**Issue by fonsecamar** [Azure/Real-time-Payment-Transaction-Processing-at-Scale#14]
ERROR: C:\Temp\Azure\Real-time-Payment-Transaction-Processing-at-Scale\infrastructure\main.bicep(116,12) : Error BCP091: An error occurred reading file. Could not find a part of the path 'C:\Temp\Azure\Real-time-Payment-Transaction-Processing-at-Scale\infrastructure\AKS-Construction\bicep\main.bicep'.

Repo https://github.com/AzureCosmosDB/RealTimeTransactions/tree/master/infrastructure had a working version.

**Comment by joelhulen** [comment]
@fonsecamar can you please verify that you included the `--recurse-submodules` command when you cloned the repo? It looks like you're missing those modules.

`git clone --recurse-submodules https://github.com/Azure/Real-time-Payment-Transaction-Processing-at-Scale.git`

This is documented in each of the deployment types (standard, VM, and cloud shell)

**Comment by fonsecamar** [comment]
@joelhulen , I did include the --recurse-submodules, but it seems there is a missing link in the repo.
Below is a side by side repo comparison.

![image](https://github.com/Azure/Real-time-Payment-Transaction-Processing-at-Scale/assets/20073945/88b06b48-b813-4683-b809-9a2620bf3d23)

**Comment by joelhulen** [comment]
@fonsecamar please try again. I just merged a PR from @hatboyzero to add this back in.

**Comment by fonsecamar** [comment]
@joelhulen , it solved the reference issue, but it's now failing with a different error.

ERROR: C:\Temp\Azure\Real-time-Payment-Transaction-Processing-at-Scale\infrastructure\AKS-Construction\bicep\main.bicep(130,16) : Error BCP104: The referenced module has errors.
C:\Temp\Azure\Real-time-Payment-Transaction-Processing-at-Scale\infrastructure\AKS-Construction\bicep\network.bicep(173,5) : Error BCP353: The variables "aks_podSubnet", "aks_podsubnet" differ only in casing. The ARM deployments engine is not case sensitive and will not be able to distinguish between them.
C:\Temp\Azure\Real-time-Payment-Transaction-Processing-at-Scale\infrastructure\AKS-Construction\bicep\network.bicep(192,5) : Error BCP353: The variables "aks_podSubnet", "aks_podsubnet" differ only in casing. The ARM deployments engine is not case sensitive and will not be able to distinguish between them.
C:\Temp\Azure\Real-time-Payment-Transaction-Processing-at-Scale\infrastructure\main.bicep(116,12) : Error BCP104: The referenced module has errors.

**Comment by markjbrown** [comment]
Hey @joelhulen can you guys take a look at this ASAP? Really want to get these fully baked ASAP.

Thanks!!!

**Comment by joelhulen** [comment]
@fonsecamar and @markjbrown the casing issue should be resolved now. Can you please do a new clone (with recurse sub-modules) and try again?

**Comment by fonsecamar** [comment]
@joelhulen , it looks like the casing issue is still there.

Those are the source lines with the issue under the branch linked:
https://github.com/hatboyzero/AKS-Construction/blob/fce5131e1344861a4700b4d4e688f096f2469ece/bicep/network.bicep#L173
https://github.com/hatboyzero/AKS-Construction/blob/fce5131e1344861a4700b4d4e688f096f2469ece/bicep/network.bicep#L192

I just changed locally and the deployment is now running.

`var **aks_basePodSubnet** =  {
  name: aks_podSubnet_name
  properties: union({
      addressPrefix: vnetPodAddressPrefix
    }, privateLinks ? {
      privateEndpointNetworkPolicies: 'Disabled'
      privateLinkServiceNetworkPolicies: 'Enabled'
    } : {}, natGateway ? {
      natGateway: {
        id: natGw.id
      }
    } : {}, azureFirewalls ? {
      routeTable: {
        id: vnet_udr.id //resourceId('Microsoft.Network/routeTables', routeFwTableName)
      }
    }: {})
}

var aks_subnet = networkSecurityGroups ? union(aks_baseSubnet, nsgAks.outputs.nsgSubnetObj) : aks_baseSubnet
var aks_podsubnet = networkSecurityGroups ? union(**aks_basePodSubnet**, nsgAks.outputs.nsgSubnetObj) : **aks_basePodSubnet**`

**Comment by joelhulen** [comment]
@hatboyzero can you please double-check this casing issue? I remember you said you found the root cause the other day.

**Comment by fonsecamar** [comment]
@joelhulen and @hatboyzero , the code snippet I posted solved the deployment.

**Comment by fonsecamar** [comment]
@joelhulen and @hatboyzero , looks like this deployment issue has been fixed.
Closing the issue.
